/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Treew({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/treew-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Bark01_2_Bark01_SHD_0.geometry} material={nodes.Bark01_2_Bark01_SHD_0.material} />
            <mesh
              geometry={nodes.Bark01_2_Bark01_SHD_0001.geometry}
              material={nodes.Bark01_2_Bark01_SHD_0001.material}
            />
            <mesh
              geometry={nodes.Bark01_2_Bark01_SHD_0002.geometry}
              material={nodes.Bark01_2_Bark01_SHD_0002.material}
            />
            <mesh
              geometry={nodes.Leaf01_2_Leaf01_su_SHD_0.geometry}
              material={nodes.Leaf01_2_Leaf01_su_SHD_0.material}
            />
            <mesh
              geometry={nodes.Leaf01_2_Leaf01_su_SHD_0001.geometry}
              material={nodes.Leaf01_2_Leaf01_su_SHD_0001.material}
            />
            <mesh
              geometry={nodes.Leaf01_2_Leaf01_su_SHD_0002.geometry}
              material={nodes.Leaf01_2_Leaf01_su_SHD_0002.material}
            />
            <mesh
              geometry={nodes.Leaf01_2_Leaf01_su_SHD_0003.geometry}
              material={nodes.Leaf01_2_Leaf01_su_SHD_0003.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/treew-transformed.glb')
